"use client"

import {
  ChatContainerContent,
  ChatContainerRoot,
} from "@/components/ai/chat-container"
import {
  CodeBlock,
  CodeBlockCode,
} from "@/components/ai/code-block"
import { JSXPreview } from "@/components/ai/jsx-preview"
import { Message, MessageAvatar, MessageContent } from "@/components/ai/message"
import {
  PromptInput,
  PromptInputActions,
  PromptInputTextarea,
} from "@/components/ai/prompt-input"
import { Reasoning, ReasoningContent, ReasoningTrigger } from "@/components/ai/reasoning"
import { ResponseStream, useTextStream } from "@/components/ai/response-stream"
import { ThinkingBar } from "@/components/ai/thinking-bar"
import { Button } from "@/components/ui/button"
import { Copy, Play, Send, Terminal } from "lucide-react"
import { useState } from "react"

function StreamingCode({ code }: { code: string }) {
  const { displayedText } = useTextStream({ textStream: code, speed: 40 })
  return <CodeBlockCode code={displayedText} language="tsx" />
}

export function CodeEditorLayout() {
  const [input, setInput] = useState("")
  const [isLoading, setIsLoading] = useState(false)
  const [generatedCode, setGeneratedCode] = useState<string | null>(null)
  const [showPreview, setShowPreview] = useState(false)

  const handleSubmit = () => {
    if (!input.trim()) return
    setIsLoading(true)
    setGeneratedCode(null)
    setShowPreview(false)

    // Simulate generating code
    setTimeout(() => {
      setGeneratedCode(`<div className="p-4 rounded-lg border bg-blue-50 border-blue-200">
  <h3 className="text-lg font-bold text-blue-900">Dynamic Component</h3>
  <p className="text-blue-700">I was generated by AI!</p>
  <button className="mt-2 px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600">
    Click Me
  </button>
</div>`)
      setIsLoading(false)
    }, 2000)
  }

  return (
    <div className="grid h-[800px] w-full grid-cols-1 gap-4 md:grid-cols-2">
      <div className="flex flex-col rounded-lg border bg-background shadow-sm">
        <div className="flex items-center justify-between border-b px-4 py-3">
          <h2 className="text-lg font-semibold">Code Assistant</h2>
          <Button variant="ghost" size="icon">
            <Terminal className="h-4 w-4" />
          </Button>
        </div>
        
        <ChatContainerRoot className="flex-1 p-4">
          <ChatContainerContent className="space-y-6">
            <Message>
              <MessageAvatar
                src="https://github.com/openai.png"
                alt="AI"
                fallback="AI"
              />
              <MessageContent className="w-full">
                Ask me to generate a UI component.
              </MessageContent>
            </Message>

            {isLoading && (
              <div className="space-y-4 pl-11">
                <ThinkingBar />
              </div>
            )}

            {generatedCode && !isLoading && (
              <div className="space-y-4 pl-11">
                <Reasoning>
                  <ReasoningTrigger>Analyzed Request</ReasoningTrigger>
                  <ReasoningContent className="space-y-2">
                    <ResponseStream textStream="The user requested a UI component. I will generate a JSX snippet using Tailwind CSS." />
                  </ReasoningContent>
                </Reasoning>
                
                <div className="rounded-xl border bg-card text-card-foreground shadow-sm">
                  <div className="flex items-center justify-between border-b px-4 py-2">
                    <span className="text-xs text-muted-foreground">tsx</span>
                    <Button variant="ghost" size="icon" className="h-8 w-8">
                      <Copy className="h-3 w-3" />
                    </Button>
                  </div>
                  <CodeBlock className="border-0 shadow-none">
                    <StreamingCode code={generatedCode} />
                  </CodeBlock>
                </div>
              </div>
            )}
          </ChatContainerContent>
        </ChatContainerRoot>

        <div className="p-4 border-t">
          <PromptInput
            value={input}
            onValueChange={setInput}
            onSubmit={handleSubmit}
            isLoading={isLoading}
          >
            <PromptInputTextarea placeholder="Generate a card component..." />
            <PromptInputActions className="justify-end pt-2">
              <Button
                size="sm"
                onClick={handleSubmit}
                disabled={!input.trim() || isLoading}
              >
                <Send className="mr-2 h-4 w-4" />
                Generate
              </Button>
            </PromptInputActions>
          </PromptInput>
        </div>
      </div>

      <div className="hidden flex-col rounded-lg border bg-muted/30 md:flex">
        <div className="flex items-center justify-between border-b bg-background px-4 py-3">
          <h2 className="text-lg font-semibold">Live Preview</h2>
          <Button 
            variant="outline" 
            size="sm" 
            onClick={() => setShowPreview(true)}
            disabled={!generatedCode}
          >
            <Play className="mr-2 h-4 w-4" />
            Run Code
          </Button>
        </div>
        <div className="flex-1 flex items-center justify-center p-8">
           {showPreview && generatedCode ? (
             <div className="w-full max-w-md">
               <JSXPreview jsx={generatedCode} />
             </div>
           ) : (
             <div className="flex flex-col items-center justify-center space-y-4 text-muted-foreground">
               <Terminal className="h-12 w-12 opacity-20" />
               <p>Click "Run Code" to see the preview.</p>
             </div>
           )}
        </div>
      </div>
    </div>
  )
}
